### ISSUE TITLE
Update dependancy

### ISSUE THREAD

**Issue by ronnievisser** [fhteam/laravel-amqp#10]
Hi,

When installing I see following note in my log files

Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

Can you update the dependancy?

**Comment by ronnievisser** [comment]
is this going to happen anytime soon?

**Comment by FractalizeR** [comment]
This is done in #11 after we make it a release. I'm sorry that you haven't received a reply for so long.

**Comment by FractalizeR** [comment]
Addressed. Currently unstable in master. After testing we'll mark that 3.0
