### ISSUE TITLE
Installation Difficulties

### ISSUE THREAD

**Issue by milsanore** [fhteam/laravel-amqp#12]
Just an fyi for anyone else installing this excellent library:

1) If you receive the error: 
"FatalErrorException: Class Forumhouse\LaravelAmqp\Queue\AMQPQueue contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\Queue::size)"

you are probably on v2.0 - I am using the master branch and it works fine.

2) make sure to install php extensions:
- mbstring
- bcmath

3) If your queues already exist you need to set 
`'declare_queues' => false`
otherwise there is a hard-to-understand error

all the best, and thank you for the great library!

**Comment by FractalizeR** [comment]
Should we, may be, implement some run-time checking there? There is nothing so frustrating as a vague error in a library you like.
