### ISSUE TITLE
Method: "connection_close" not implemented by class: PhpAmqpLib\Channel\AMQPChannel

### ISSUE THREAD

**Issue by congnghiakhiem** [fhteam/laravel-amqp#14]
When I change 'channel_id' => null to 'channel_id' => 'channelname',
Error occur: 
Method: "connection_close" not implemented by class: PhpAmqpLib\Channel\AMQPChannel
Plz help me !

**Comment by FractalizeR** [comment]
Why do you do that? Have you created a specific channel?

**Comment by eyudkin** [comment]
Faced with this problem, when tried to pass **string** channel name to $connection->channel() method which awaits `@param int $channel_id`.
May be we just need some validation for this param.

**Comment by FractalizeR** [comment]
Can you get us a stack trace?

**Comment by FractalizeR** [comment]
Looks like this is no longer relevant for our other library users. Closing. Please reopen it if you will have more details.
