### ISSUE TITLE
Can I get the queue count using laravel-amqp?

### ISSUE THREAD

**Issue by milsanore** [fhteam/laravel-amqp#17]
Hi,

I would like to enqueue jobs based on how loaded a queue is. That is to say, I want some mechanism of rate-limiting. So, if the queue has >20 messages, wait, else enqueue a jobs.

I was just wondering if the laravel-amqp layer can be used to check the number of messages on a RabbitMQ queue?

Thanks!

EDIT: current solution is the following, just checking if there is a better abstracted solution, thx

```
public static function getQueueCount($queueName)
	{
		$qHost = config("queue.connections.amqp.host");
		$qPort = config("queue.connections.amqp.port");
		$qUser = config("queue.connections.amqp.user");
		$qPwd  = config("queue.connections.amqp.password");

		$connection = new AMQPStreamConnection($qHost, $qPort, $qUser, $qPwd);
		$channel = $connection->channel();

		list($queue, $messageCount, $consumerCount) = $channel->queue_declare($queueName, true);

		return $messageCount;
	}
```

**Comment by FractalizeR** [comment]
I think we can incorporate this into our library also ;)

**Comment by FractalizeR** [comment]
```size()``` implemented for queues.
