### ISSUE TITLE
Support for message-priority

### ISSUE THREAD

**Issue by milsanore** [fhteam/laravel-amqp#18]
Hi, 
As always, thank you for the awesome library, it's the backbone of my system.
My worker queue currently has >10m messages on it, which get processed over several days. So for any new messages that I enqueue, I have to wait a few days. 
I just read that RabbitMQ 3.5 supports message-priority. This would be very useful to make a few ad-hoc messages get prioritised, while the rest of the messages on the queue can take as long as they need to complete.
I'm wondering if this can be supported by the library, or is Laravel going to be a problem?
Thanks!

**Comment by FractalizeR** [comment]
You can declare a queue with priority support by providing ```new AMQPTable(['x-max-priority' => 5])``` as one of the ```$queueFlags```. Then you can set desired queue priority for newly pushed messages via ```$messageProperties``` by providing ```'priority' => 1```.

I've provided a setter for ```$messageProperties``` in a \Forumhouse\LaravelAmqp\Queue\AMQPQueue with 5d25b20f7cb93b145fe6f5f82d70205c89f37b66 if you need to change after the queue was initialized.

Please try and let me know if it works for you

**Comment by milsanore** [comment]
Amazing stuff, thanks @FractalizeR!

**Comment by FractalizeR** [comment]
Welcome ;)

**Comment by milsanore** [comment]
Hi @FractalizeR, I'm implementing this now, very exciting.
I have the queue config working successfully, now I'm looking at dispatching jobs.
Is `$messageProperties` meant to be a member of my job classes, or am I meant to modify the queue on every dispatch? If so, can you provide just a one-line example of how (e.g. `Queue::connection("")->setMessageProperties(['priority' => 1])`)?

Thanks

**Comment by milsanore** [comment]
I think I've figured it out so I'll close. The implementation I'm using is below. Thanks,

```
public static function sendAmqpJob(ShouldQueue $job, string $queueName, int $priority = null)
{
	// PRIORITY JOB
	if ($priority > 0)
	{
		/** @var AMQPQueue $queue */
		$queue = Queue::connection();

		// EXTEND QUEUE-PROPERTIES WITH A MESSAGE PRIORITY
		$props = $queue->getMessageProperties();
		$props['priority'] = $priority;
		$queue->setMessageProperties($props);

		// DISPATCH JOB
		$job->onQueue($queueName);
		dispatch($job);

		// REVERT QUEUE-PROPERTIES WITH A MESSAGE PRIORITY OF "1"
		$props = $queue->getMessageProperties();
		$props['priority'] = 1;
		$queue->setMessageProperties($props);
	}
	// CLASSIC JOB
	else
	{
		$job->onQueue($queueName);
		dispatch($job);
	}
}
```
