### ISSUE TITLE
ServiceProvider not booted

### ISSUE THREAD

**Issue by robbash** [fhteam/laravel-amqp#8]
Hi,

is there a known issue with the booting of the ServiceProvider? (https://github.com/fhteam/laravel-amqp/blob/v2.0.1/src/ServiceProvider/LaravelAmqpServiceProvider.php#L22)

I'm using Lumen and had to change it to http://laravel.com/docs/5.0/providers#basic-provider-example, using a boot() function to make it work.

Haven't found your approach somewhere documented.

Cheers,
Rob

**Comment by FractalizeR** [comment]
Lumen's `register()` is documented here: http://lumen.laravel.com/docs/providers#the-register-method
Laravel's is here: http://laravel.com/docs/5.1/providers#the-register-method

Laravel's works ok for my current project.

**Comment by robbash** [comment]
Thanks for your response.

What I meant was that I couldn't find this way `$this->app->booted(...)` documented somewhere. To make your package work I had to implement the `boot` method, also documented in the two links you've posted.

Does that help to understand my issue?

Cheers

**Comment by FractalizeR** [comment]
Well, it's in Laravel's the source code. [Available starting from 5.0](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L724).

Somehow it is not yet implemented in latest Lumen. See [this](https://github.com/laravel/lumen-framework/blob/5.1/src/Application.php#L320). I really do not understand how this piece got into Lumen's production code... I guess I miss something.

**Comment by FractalizeR** [comment]
Closing since this issue is probably resolved.
