### ISSUE TITLE
Error in L5.2

### ISSUE THREAD

**Issue by ronnievisser** [fhteam/laravel-amqp#9]
Hi,

When using your package in L5.2 I get the following error:

Argument 2 passed to Illuminate\Queue\Worker::process() must be an instance of Illuminate\Contracts\Queue\Job, instance of Forumhouse\LaravelAmqp\Jobs\AMQPJob given, called in /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php on line 159 and defined

**Comment by ronnievisser** [comment]
Using the 2.\* branch fixed this

**Comment by FractalizeR** [comment]
Yep. We should have documented the fact, that V2 is L5 ready. Sorry.
